# Generated by Django 3.2.3 on 2022-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
