# Generated by Django 3.2.3 on 2022-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
