# Generated by Django 3.2.3 on 2022-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_employee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
