# Generated by Django 3.2.3 on 2022-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221101_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.ImageField(null=True, upload_to='file/'),
        ),
    ]
