# Generated by Django 3.2.3 on 2022-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_employee_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.ImageField(null=True, upload_to='file/'),
        ),
    ]
