# Generated by Django 3.2.3 on 2022-11-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_employee_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='file',
        ),
    ]
